### ISSUE TITLE
Choosing  Rmin as X axis title 

### ISSUE THREAD

**Issue by suvadip31** [BogdanCiambur/PROFILER#2]
Hi Bogdan,

Thank you very much for a new version of PROFILER. I am analyzing minor axis of a galaxy using the inclined disk model. How can I write the X axis title as Rmin instead of Rmaj.

**Comment by BogdanCiambur** [comment]
Hi Suvadip,

In the source file "profiler.py", you need to replace lines 973 and 1190 from:

  _if (axistype.get() == 'maj'): plt.xlabel(r'$R_{\rm **maj**}$ '+xunEn.get(), fontsize=20)_

to:

  _if (axistype.get() == 'maj'): plt.xlabel(r'$R_{\rm **min**}$ '+xunEn.get(), fontsize=20)_

I intend to make this an option directly in the GUI in a future release, for now unfortunately you'll need to change source code... Hope this helps

Cheers,

**Comment by suvadip31** [comment]
Hi Bogdan,

Thanks a lot!!.  I just did that. This surely helps! Thank you very much again.

Suvadip
